apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kasten
  namespace: monitoring  
spec:  
  port:
    targetPort: grafana
  tls:
    termination: edge
  to:
    kind: Service
    name: kasten-service
    weight: 100
  wildcardPolicy: None