apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: kasten
  namespace: monitoring
  labels:
    dashboards: "kasten"
spec:
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: kasten
      admin_password: <redacted>
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              readinessProbe:
                failureThreshold: 3
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: kasten-pvc